// Based on RECYCLE's Grammar
// The first draft of this file was generated by Copilot
import { AbstractParseTreeVisitor } from "antlr4ts/tree";

import {
    GameContext,
    DeclareContext,
    SetupContext,
    ScoringContext,
    StageContext,
    EndconditionContext,
    MultiactionContext,
    CondactContext,
    AggContext,
    LetContext,
    ActionContext,
    PlayercreateContext,
    TeamcreateContext,
    TeamsContext,
    DeckcreateContext,
    DeckContext,
    AttributeContext,
    InitpointsContext,
    UpdatepointsContext,
    AwardsContext,
    SubawardContext,
    MoveactionContext,
    CopyactionContext,
    RemoveactionContext,
    SetactionContext,
    SetstractionContext,
    IncactionContext,
    DecactionContext,
    CycleactionContext,
    TurnactionContext,
    RepeatContext,
    AddContext,
    MultContext,
    SubtractContext,
    DivideContext,
    ModContext,
    ExponentContext,
    IntContext,
    IntgrContext,
    BooleanContext,
    VariContext,
    VarsContext,
    VarpContext,
    VarbContext,
    VarContext,
    NamegrContext,
    TypedContext,
    RawstorageContext,
    StrstorageContext,
    PointstorageContext,
    WhopContext,
    WhotContext,
    WhoContext,
    CardContext,
    RangeContext,
    CollectionContext,
    ScoreContext,
    ScoremaxContext,
    ScoreminContext,
    SizeofContext,
    RandomContext,
    TriangularContext,
    FibonacciContext,
    AggiContext,
    SwapactionContext,
    ShuffleactionContext,
    CstorageContext,
    TidContext,
    PidContext,
    SumContext,
    MinofContext,
    MaxofContext,
    FilterContext,
    TeampContext,
    OwnerContext,
    StrContext,
    CardattContext,
    MemstorageContext,
    IndexedContext,
    SubsetContext,
    PartitionContext,
    SortofContext,
    DisjunctionofContext,
    IntersectofContext,
    UnionofContext,
    AggcsContext,
    RunContext,
    RunsequenceContext,
    SequenceContext,
    BasecstorageContext,
    Multiaction2Context,
    LocpreContext,
    LocdescContext,
    AggbContext,
    CstoragecollectionContext,
    VaroContext,
    VarcContext,
    VarcsContext,
    VarcscContext,
    VarcardContext,
} from "./generated/RecycleParser";

import { RecycleVisitor } from "./generated/RecycleVisitor";

export interface FunctionNode {
    kind: "Function";

    operator: string;

    arguments: ExpressionNode[];
}

export interface StorageNode {
    kind: "Storage";

    owner:
        | PlayerNode
        | TeamNode
        | "game";

    storageType:
        | "sto"
        | "str"
        | "vloc"
        | "iloc"
        | "hloc"
        | "oloc"
        | "mem";

    name: ExpressionNode;

    index?: ExpressionNode;
}

export interface VariableNode {
    kind: "Variable";

    name: string;

    variableKind:
        | "generic"
        | "int"
        | "string"
        | "boolean"
        | "owner"
        | "player"
        | "card"
        | "collection"
        | "cardCollection"
        | "cardCollectionCollection";
}


export interface LiteralNode {
    kind: "Literal";

    valueType:
        | "int"
        | "string"
        | "boolean";

    value:
        | number
        | string
        | boolean;
}

export interface RangeNode {
    kind: "Range";
    start: ExpressionNode;
    end: ExpressionNode;
}

export type ExpressionNode =
    | LiteralNode
    | VariableNode
    | FunctionNode
    | RawStorageNode
    | StringStorageNode
    | PointStorageNode
    | CollectionStorageNode
    | CollectionNode
    | FilterNode
    | RangeNode
    | SequenceNode
    | RunNode
    | BooleanNode
    | CardNode
    | PlayerNode
    | TeamNode
    | ScoreNode
    | ScoreMaxNode
    | ScoreMinNode
    | ScoreSumNode
    | SizeNode
    | PlayerIdNode
    | TeamIdNode
    | IntegerAggregateNode
    | AggregateCollectionNode;

export interface CreatePlayersNode {
    kind: "CreatePlayers";

    count: ExpressionNode;
}

export interface TeamCreateNode {
    kind: "CreateTeams";

    teams: number[][];
}

export interface DeckCreateNode {
    kind: "CreateDeck";

    name?: ExpressionNode;

    location: StorageNode;

    attributes: string[][];
}

export interface MoveNode {
    kind: "Move";

    from: ExpressionNode;
    to: ExpressionNode;
}

export interface SwapNode {
    kind: "Swap";

    left: ExpressionNode;
    right: ExpressionNode;
}

export interface RememberNode {
    kind: "Remember";

    source: ExpressionNode;
    destination: ExpressionNode;
}

export interface ForgetNode {
    kind: "Forget";

    card: ExpressionNode;
}

export interface InitPointsNode {
    kind: "InitPoints";

    storage: PointStorageNode;

    awards: AwardNode[];
}

export interface UpdatePointsNode {
    kind: "UpdatePoints";

    storage: PointStorageNode;

    awards: AwardNode[];
}

export interface AwardNode {
    kind: "Award";

    categories: SubAwardNode[];

    value: ExpressionNode;
}

export interface SubAwardNode {
    kind: "SubAward";

    left: ExpressionNode;

    right: ExpressionNode;
}


export interface CycleNode {
    kind: "Cycle";

    direction:
        | "next"
        | "current";

    target: PlayerNode;
}

export interface TurnPassNode {
    kind: "TurnPass";
}


export interface ShuffleNode {
    kind: "Shuffle";

    mode:
        | "normal"
        | "faro";

    source: ExpressionNode;

    secondarySource?: ExpressionNode;
}


export interface RepeatNode {
    kind: "Repeat";

    repetition:
        | FixedRepeatNode
        | RepeatAllNode;
}

export interface FixedRepeatNode {
    kind: "FixedRepeat";

    count: ExpressionNode;

    action: ActionNode;
}

export interface RepeatAllNode {
    kind: "RepeatAll";

    action:
        | MoveNode
        | ForgetNode;
}

export interface IntegerAggregateNode {
    kind: "IntegerAggregate";

    collection: ExpressionNode;

    variable: string;

    storage: RawStorageNode;
}

export interface ScoreNode {
    kind: "Score";

    card: CardNode;

    scoreSource: PointStorageNode;
}

export interface ScoreMaxNode {
    kind: "ScoreMax";
    collection: ExpressionNode;
    scoreSource: PointStorageNode;
}

export interface ScoreMinNode {
    kind: "ScoreMin";
    collection: ExpressionNode;
    scoreSource: PointStorageNode;
}

export interface ScoreSumNode {
    kind: "ScoreSum";
    collection: ExpressionNode;
    scoreSource: PointStorageNode;
}

export interface SizeNode {
    kind: "Size";

    collection: ExpressionNode;
}

export interface PlayerIdNode {
    kind: "PlayerId";

    player: PlayerNode;
}

export interface TeamIdNode {
    kind: "TeamId";

    team: TeamNode;
}

export type BooleanNode =
    | BooleanLiteralNode
    | BooleanOperatorNode
    | ComparisonNode
    | NegationNode
    | QuantifierNode
    | BooleanAggregateNode;

export interface BooleanLiteralNode {
    kind: "BooleanLiteral";

    value: boolean;
}

export interface BooleanOperatorNode {
    kind: "BooleanOperator";

    operator:
        | "and"
        | "or";

    operands: ExpressionNode[];
}

export interface ComparisonNode {
    kind: "Comparison";

    operator:
        | "=="
        | "!="
        | "<"
        | ">"
        | "<="
        | ">=";

    left: ExpressionNode;

    right: ExpressionNode;
}

export interface NegationNode {
    kind: "Negation";

    value: ExpressionNode;
}

export interface QuantifierNode {
    kind: "Quantifier";

    mode:
        | "any"
        | "all";

    collection: ExpressionNode;

    variable: string;

    predicate: BooleanNode;
}

export interface PlayerReferenceNode {
    kind: "PlayerReference";

    descriptor:
        | "current"
        | "next"
        | "previous"
        | number;
}

export interface OwnerPlayerNode {
    kind: "OwnerPlayer";

    card: CardNode;
}

export interface PlayerVariableNode {
    kind: "PlayerVariable";

    variable: string;
}

export type PlayerNode =
    | PlayerReferenceNode
    | OwnerPlayerNode
    | PlayerVariableNode;

export interface SetNode {
    kind: "Set";
    storage: RawStorageNode;
    value: ExpressionNode;
}

export interface SetStringNode {
    kind: "SetString";
    storage: StringStorageNode;
    value: ExpressionNode;
}

export interface IncrementNode {
    kind: "Increment";
    storage: RawStorageNode;
    amount?: ExpressionNode;
}


export interface DecrementNode {
    kind: "Decrement";
    storage: RawStorageNode;
    amount?: ExpressionNode;
}


export type ActionNode =
    | CreatePlayersNode
    | TeamCreateNode
    | DeckCreateNode
    | InitPointsNode
    | UpdatePointsNode
    | CycleNode
    | SetNode
    | SetStringNode
    | IncrementNode
    | DecrementNode
    | MoveNode
    | SwapNode
    | RememberNode
    | ForgetNode
    | ShuffleNode
    | TurnPassNode
    | RepeatNode
    | ConditionalActionNode;

export interface ConditionalActionNode {
    kind: "ConditionalAction";
    condition?: ExpressionNode;
    action:
        | ActionNode
        | MultiActionNode;
}

export interface ChoiceNode {
    kind: "Choice";
    actions: ConditionalActionNode[];
}

export interface DoNode {
    kind: "Do";
    actions: ConditionalActionNode[];
}

export interface LetNode {
    kind: "Let";
    variable: string;
    variableType: RecycleType;
    body:
        | ActionNode
        | MultiActionNode
        | ConditionalActionNode;
}

export interface AggregateNode {
    kind: "Aggregate";
    aggregateType: "all" | "any";
    collection: ExpressionNode;
    variable: string;
    action: ConditionalActionNode;
}

export type StorageOwner =
    | "game"
    | PlayerNode
    | TeamNode;

export interface PointStorageNode {
    kind: "PointStorage";
    owner: StorageOwner;
    key: ExpressionNode;
}

export interface RawStorageNode {
    kind: "RawStorage";
    owner: StorageOwner;
    key: ExpressionNode;
}

export interface StringStorageNode {
    kind: "StringStorage";
    owner: StorageOwner;
    key: ExpressionNode;
}

export interface CollectionStorageNode {
    kind: "CollectionStorage";
    location: LocationReferenceNode;
}

export interface LocationReferenceNode {
    kind: "LocationReference";
    owner:
        | PlayerNode
        | TeamNode;
    locationType:
        | "hand"
        | "table"
        | "deck"
        | "discard"
        | string;

    index?: ExpressionNode;
}

export interface CardNode {
    kind: "Card";
    selector:
        | "top"
        | "bottom"
        | "index"
        | "max"
        | "min"
        | "variable";
    collection?: ExpressionNode;
    index?: ExpressionNode;
    scoreSource?: PointStorageNode;
    variable?: string;
}

export interface CollectionNode {
    kind: "Collection";

    operation:
        | "filter"
        | "union"
        | "intersect"
        | "disjunction"
        | "sort"
        | "partition"
        | "subset"
        | "runs"
        | "indexed"
        | "range"
        | "sequence";

    arguments: ExpressionNode[];
}

export interface FilterNode {
    kind: "Filter";

    source: ExpressionNode;

    variable: string;

    predicate: BooleanNode;
}

export interface AggregateCollectionNode {
    kind: "AggregateCollection";

    source: ExpressionNode;

    variable: string;

    collection: ExpressionNode;
}

export interface SequenceNode {
    kind: "Sequence";

    collection: ExpressionNode;

    length: ExpressionNode;
}

export interface RunNode {
    kind: "Run";

    collection: ExpressionNode;

    length: ExpressionNode;

    scoreSource: PointStorageNode;
}

export interface BooleanAggregateNode {
    kind: "BooleanAggregate";
    collection: ExpressionNode;
    variable: string;
    predicate: BooleanNode;
}

export type MultiActionNode =
    | ChoiceNode
    | DoNode
    | LetNode
    | AggregateNode;

export interface ScoringNode {
    kind: "Scoring";

    mode: "min" | "max";

    scoreTarget: ExpressionNode;
}

export interface TeamReferenceNode {
    kind: "TeamReference";

    descriptor:
        | "current"
        | "next"
        | "previous"
        | number;
}

export interface TeamOfPlayerNode {
    kind: "TeamOfPlayer";
    player: PlayerNode;
}

export type TeamNode =
    | TeamReferenceNode
    | TeamOfPlayerNode;


export interface SetupNode {
    kind: "Setup";

    playerCount: ExpressionNode;

    teamCreation?: TeamCreateNode;

    setupActions: (
        | DeckCreateNode
        | RepeatNode
    )[];
}

export type RecycleType =
    | "int"
    | "boolean"
    | "string"
    | "collection";

export interface DeclarationNode {
    kind: "Declaration";

    variable: string;
    variableType: RecycleType;
}


export interface GameNode {
    kind: "Game";

    declarations: DeclarationNode[];
    setup: SetupNode;

    body: BodyNode[];

    scoring: ScoringNode;
}

export interface StageNode {
    kind: "Stage";

    scope: "player" | "team";

    mode:
        | "normal"
        | "simultaneous"
        | "once";

    endCondition?: ExpressionNode;

    body: (
        | StageNode
        | MultiActionNode
    )[];
}

export type BodyNode =
    | StageNode
    | MultiActionNode;

export type RecycleNode =
    | GameNode
    | StageNode
    | SetupNode
    | ScoringNode
    | StorageNode
    | DeclarationNode
    | ActionNode
    | ExpressionNode
    | AwardNode
    | SubAwardNode;

export interface SourceLocation {
    line?: number;
    column?: number;
}

type VisitorResult =
    | RecycleNode
    | number[]
    | string
    | string[]
    | string[][]
    | MultiActionNode;


export class ASTBuilder
    extends AbstractParseTreeVisitor<VisitorResult>
    implements RecycleVisitor<VisitorResult>
{
    protected defaultResult(): RecycleNode {
        throw new Error("Unhandled grammar node");
    }

    private variableName(text: string): string {
        return text.startsWith("'")
            ? text.substring(1)
            : text;
    }

    private intLiteral(value: number): LiteralNode {
        return {
            kind: "Literal",
            valueType: "int",
            value,
        };
    }

    private resolveType(ctx: TypedContext): RecycleType {
        if (ctx.int()) return "int";
        if (ctx.boolean()) return "boolean";
        if (ctx.collection()) return "collection";
        return "string";
    }

    visitGame(ctx: GameContext): GameNode {
        const body: BodyNode[] = [];

        for (const stage of ctx.stage()) {
            body.push(this.visit(stage) as StageNode);
        }

        for (const action of ctx.multiaction()) {
            body.push(this.visit(action) as MultiActionNode);
        }

        return {
            kind: "Game",
            declarations:
                ctx.declare().map(d =>
                    this.visit(d) as DeclarationNode
                ),
            setup:
                this.visit(ctx.setup()) as SetupNode,
            body,
            scoring:
                this.visit(ctx.scoring()) as ScoringNode,
        };
    }

    visitDeclare(ctx: DeclareContext): DeclarationNode {
        return {
            kind: "Declaration",
            variable: this.variableName(ctx.var().text),
            variableType: this.resolveType(ctx.typed()),
        };
    }

    visitSetup(ctx: SetupContext): SetupNode {
        const team = ctx.teamcreate();

        const initial: SetupNode = {
            kind: "Setup",

            playerCount:
                (this.visit(ctx.playercreate()) as CreatePlayersNode)
                    .count,

            setupActions: [
                ...ctx.deckcreate().map(d =>
                    this.visit(d) as DeckCreateNode
                ),
                ...ctx.repeat().map(r =>
                    this.visit(r) as RepeatNode
                )
            ]
        };
        
        return team ? {
            ...initial, teamCreation: this.visit(team) as TeamCreateNode
        } : initial;
    }

    visitScoring(ctx: ScoringContext): ScoringNode {
        return {
            kind: "Scoring",
            mode: "max",
            scoreTarget: this.visit(ctx.int()) as ExpressionNode,
        };
    }

    visitStage(ctx: StageContext): StageNode {
        const body: (StageNode | MultiActionNode)[] = [];

        for (const stage of ctx.stage()) {
            body.push(this.visit(stage) as StageNode);
        }

        for (const action of ctx.multiaction()) {
            body.push(this.visit(action) as MultiActionNode);
        }

        const endCondition = ctx.endcondition();

        const initial: StageNode = {
            kind: "Stage",
            scope: "player",
            mode: "normal",
            body,
        };

        return endCondition ? { ...initial, endCondition: this.visit(ctx.endcondition()!) as ExpressionNode } : initial;
    }

    visitEndcondition(ctx: EndconditionContext): ExpressionNode {
        return this.visit(ctx.boolean()) as ExpressionNode;
    }

    visitPlayercreate(ctx: PlayercreateContext): CreatePlayersNode {
        return {
            kind: "CreatePlayers",
            count: this.visit(ctx.int()) as ExpressionNode,
        };
    }

    visitTeamcreate(ctx: TeamcreateContext): TeamCreateNode {
        return {
            kind: "CreateTeams",
            teams: ctx.teams().map(t =>
                this.visit(t) as number[]
            )
        };
    }

    visitTeams(ctx: TeamsContext): number[] {
        const ints = ctx.INTNUM();

        return ints.map(i => Number(i.text));
    }

    visitDeckcreate(ctx: DeckcreateContext): DeckCreateNode {
        const name = ctx.str();

        const initial: DeckCreateNode = {
            kind: "CreateDeck",
            location:
                this.visit(ctx.cstorage()) as StorageNode,
            attributes:
                (this.visit(ctx.deck()) as string[][])
        };

        return name ?
            { ...initial, name: this.visit(ctx.str()!) as ExpressionNode } :
            initial;
    }

    visitDeck(ctx: DeckContext): string[][] {
        return ctx.attribute().map(a =>
            this.visit(a) as string[]
        );
    }

    visitAttribute(ctx: AttributeContext): string[] {
        return ctx.namegr().map(n => n.text);
    }

    visitMoveaction(ctx: MoveactionContext): MoveNode {
        return {
            kind: "Move",
            from: this.visit(ctx.card(0)) as ExpressionNode,
            to: this.visit(ctx.card(1)) as ExpressionNode,
        };
    }

    visitCopyaction(ctx: CopyactionContext): RememberNode {
        return {
            kind: "Remember",
            source: this.visit(ctx.card(0)) as ExpressionNode,
            destination: this.visit(ctx.card(1)) as ExpressionNode,
        };
    }

    visitRemoveaction(ctx: RemoveactionContext): ForgetNode {
        return {
            kind: "Forget",
            card: this.visit(ctx.card()) as ExpressionNode,
        };
    }

    visitSetaction(ctx: SetactionContext): SetNode {
        return {
            kind: "Set",
            storage:
                this.visit(ctx.rawstorage()) as RawStorageNode,
            value:
                this.visit(ctx.int()) as ExpressionNode,
        };
    }

    visitSetstraction(ctx: SetstractionContext): SetStringNode {
        return {
            kind: "SetString",
            storage:
                this.visit(ctx.strstorage()) as StringStorageNode,
            value:
                this.visit(ctx.str()) as ExpressionNode,
        };
    }

    visitIncaction(ctx: IncactionContext): IncrementNode {
        return {
            kind: "Increment",

            storage:
                this.visit(ctx.rawstorage()) as RawStorageNode,

            amount:
                ctx.int()
                    ? this.visit(ctx.int()!) as ExpressionNode
                    : this.intLiteral(1),
        };
    }

    visitDecaction(ctx: DecactionContext): DecrementNode {
        return {
            kind: "Decrement",

            storage:
                this.visit(ctx.rawstorage()) as RawStorageNode,

            amount:
                ctx.int()
                    ? this.visit(ctx.int()!) as ExpressionNode
                    : this.intLiteral(1),
        };
    }

    visitCycleaction(ctx: CycleactionContext): CycleNode {
        return {
            kind: "Cycle",

            direction: "next",

            target:
                ctx.whop()
                    ? this.visit(ctx.whop()!) as PlayerNode
                    : this.visit(ctx.varp()!) as unknown as PlayerNode
        };
    }

    visitTurnaction(_ctx: TurnactionContext): TurnPassNode {
        return {
            kind: "TurnPass"
        };
    }

    visitRepeat(ctx: RepeatContext): RepeatNode {

        const int = ctx.int();
        const action = ctx.action();

        if (int && action) {
            return {
                kind: "Repeat",
                repetition: {
                    kind: "FixedRepeat",
                    count:
                        this.visit(int) as ExpressionNode,
                    action:
                        this.visit(action) as ActionNode
                }
            };
        }

        if (ctx.moveaction()) {
            return {
                kind: "Repeat",
                repetition: {
                    kind: "RepeatAll",
                    action:
                        this.visit(ctx.moveaction()!) as MoveNode
                }
            };
        }

        return {
            kind: "Repeat",
            repetition: {
                kind: "RepeatAll",
                action:
                    this.visit(ctx.removeaction()!) as ForgetNode
            }
        };
    }

    visitAction(ctx: ActionContext): ActionNode {

        const candidates = [
            ctx.initpoints(),
            ctx.teamcreate(),
            ctx.deckcreate(),
            ctx.cycleaction(),
            ctx.setaction(),
            ctx.moveaction(),
            ctx.copyaction(),
            ctx.swapaction(),
            ctx.updatepoints(),
            ctx.incaction(),
            ctx.setstraction(),
            ctx.decaction(),
            ctx.removeaction(),
            ctx.turnaction(),
            ctx.shuffleaction(),
            ctx.repeat(),
        ];

        const found = candidates.find(x => x);

        if (!found) {
            throw new Error("Unhandled action");
        }

        return this.visit(found as any) as ActionNode;
    }

    visitInt(ctx: IntContext): ExpressionNode {

        const candidates = [
            ctx.vari(),
            ctx.sizeof(),
            ctx.mult(),
            ctx.subtract(),
            ctx.mod(),
            ctx.add(),
            ctx.divide(),
            ctx.exponent(),
            ctx.triangular(),
            ctx.fibonacci(),
            ctx.random(),
            ctx.sum(),
            ctx.rawstorage(),
            ctx.score(),
            ctx.pid(),
            ctx.tid(),
            ctx.aggi(),
            ctx.scoremax(),
            ctx.scoremin(),
            ctx.intgr(),
        ];

        const found = candidates.find(x => x);

        if (!found) {
            throw new Error("Unknown int expression");
        }

        return this.visit(found as any) as ExpressionNode;
    }

    visitIntgr(ctx: IntgrContext): LiteralNode {
        return {
            kind: "Literal",
            valueType: "int",
            value: Number(ctx.text),
        };
    }

    visitAdd(ctx: AddContext): FunctionNode {
        return {
            kind: "Function",
            operator: "+",
            arguments:
                ctx.int().map(i =>
                    this.visit(i) as ExpressionNode
                )
        };
    }

    visitMult(ctx: MultContext): FunctionNode {
        return {
            kind: "Function",
            operator: "*",
            arguments:
                ctx.int().map(i =>
                    this.visit(i) as ExpressionNode
                )
        };
    }

    visitSubtract(ctx: SubtractContext): FunctionNode {
        return {
            kind: "Function",
            operator: "-",
            arguments:
                ctx.int().map(i =>
                    this.visit(i) as ExpressionNode
                )
        };
    }

    visitDivide(ctx: DivideContext): FunctionNode {
        return {
            kind: "Function",
            operator: "/",
            arguments:
                ctx.int().map(i =>
                    this.visit(i) as ExpressionNode
                )
        };
    }

    visitMod(ctx: ModContext): FunctionNode {
        return {
            kind: "Function",
            operator: "%",
            arguments:
                ctx.int().map(i =>
                    this.visit(i) as ExpressionNode
                )
        };
    }

    visitExponent(ctx: ExponentContext): FunctionNode {
        return {
            kind: "Function",
            operator: "^",
            arguments:
                ctx.int().map(i =>
                    this.visit(i) as ExpressionNode
                )
        };
    }

    visitVari(ctx: VariContext): VariableNode {
        return {
            kind: "Variable",
            variableKind: "int",
            name: this.variableName(ctx.text),
        };
    }

    visitVars(ctx: VarsContext): VariableNode {
        return {
            kind: "Variable",
            variableKind: "string",
            name: this.variableName(ctx.text),
        };
    }

    visitVarp(ctx: VarpContext): VariableNode {
        return {
            kind: "Variable",
            variableKind: "player",
            name: this.variableName(ctx.text),
        };
    }

    visitVarb(ctx: VarbContext): VariableNode {
        return {
            kind: "Variable",
            variableKind: "boolean",
            name: this.variableName(ctx.text),
        };
    }

    visitNamegr(ctx: NamegrContext): LiteralNode {
        return {
            kind: "Literal",
            valueType: "string",
            value: ctx.text,
        };
    }

    visitRange(ctx: RangeContext): RangeNode {
        return {
            kind: "Range",
            start: this.visit(ctx.int(0)) as ExpressionNode,
            end: this.visit(ctx.int(1)) as ExpressionNode,
        };
    }

    visitRawstorage(ctx: RawstorageContext): RawStorageNode {
        return {
            kind: "RawStorage",

            owner:
                ctx.who()
                    ? this.visit(ctx.who()!) as PlayerNode | TeamNode
                    : "game",

            key:
                this.visit(ctx.str()) as ExpressionNode,
        };
    }
    visitStrstorage(ctx: StrstorageContext): StringStorageNode {
        return {
            kind: "StringStorage",

            owner:
                ctx.who()
                    ? this.visit(ctx.who()!) as PlayerNode | TeamNode
                    : "game",

            key:
                this.visit(ctx.str()) as ExpressionNode,
        };
    }
    visitPointstorage(ctx: PointstorageContext): PointStorageNode {
        return {
            kind: "PointStorage",

            owner:
                ctx.who()
                    ? this.visit(ctx.who()!) as PlayerNode | TeamNode
                    : "game",

            key:
                this.visit(ctx.str()) as ExpressionNode,
        };
    }
    visitSizeof(ctx: SizeofContext): SizeNode {
        return {
            kind: "Size",
            collection:
                this.visit(ctx.collection()) as ExpressionNode,
        };
    }
    visitRandom(ctx: RandomContext): FunctionNode {
        return {
            kind: "Function",
            operator: "random",
            arguments:
                ctx.int().map(i =>
                    this.visit(i) as ExpressionNode
                ),
        };
    }
    visitFibonacci(ctx: FibonacciContext): FunctionNode {
        return {
            kind: "Function",
            operator: "fibonacci",
            arguments: [
                this.visit(ctx.int()) as ExpressionNode,
            ],
        };
    }
    visitTriangular(ctx: TriangularContext): FunctionNode {
        return {
            kind: "Function",
            operator: "triangular",
            arguments: [
                this.visit(ctx.int()) as ExpressionNode,
            ],
        };
    }
    visitWho(ctx: WhoContext): PlayerNode | TeamNode {
        if (ctx.whop()) {
            return this.visit(ctx.whop()!) as PlayerNode;
        }

        return this.visit(ctx.whot()!) as TeamNode;
    }

   visitWhop(ctx: WhopContext): PlayerNode {

        if (ctx.owner()) {
            return this.visit(
                ctx.owner()!
            ) as OwnerPlayerNode;
        }

        const descriptor =
            ctx.whodesc()?.int();

        if (descriptor) {
            return {
                kind: "PlayerReference",

                descriptor:
                    Number(descriptor.text)
            };
        }

        return {
            kind: "PlayerReference",

            descriptor: "current"
        };
    }

    visitWhot(ctx: WhotContext): TeamNode {

        if (ctx.teamp()) {
            return this.visit(
                ctx.teamp()!
            ) as TeamNode;
        }

        const descriptor =
            ctx.whodesc()?.int();

        if (descriptor) {
            return {
                kind: "TeamReference",

                descriptor:
                    Number(descriptor.text)
            };
        }

        return {
            kind: "TeamReference",

            descriptor: "current"
        };
    }
    visitCard(ctx: CardContext): CardNode {

        if (ctx.maxof()) {
            return this.visit(ctx.maxof()!) as CardNode;
        }

        if (ctx.minof()) {
            return this.visit(ctx.minof()!) as CardNode;
        }

        if (ctx.varcard()) {
            return {
                kind: "Card",
                selector: "variable",
                variable: ctx.varcard()!.text,
            };
        }

        const collection = ctx.cstorage();

        if (ctx.int()) {
            return {
                kind: "Card",
                selector: "index",

                collection:
                    this.visit(collection!) as ExpressionNode,

                index:
                    this.visit(ctx.int()!) as ExpressionNode,
            };
        }

        return {
            kind: "Card",

            selector: "top",

            collection:
                this.visit(collection!) as ExpressionNode,
        };
    }
    visitSwapaction(ctx: SwapactionContext): SwapNode {
        const cards = ctx.card();

        return {
            kind: "Swap",
            left: this.visit(cards[0] as CardContext) as ExpressionNode,
            right: this.visit(cards[1] as CardContext) as ExpressionNode,
        };
    }
    visitShuffleaction(ctx: ShuffleactionContext): ShuffleNode {
        const stores = ctx.cstorage();

        return {
            kind: "Shuffle",

            mode: "normal",

            source:
                this.visit(stores[0] as CstorageContext) as ExpressionNode,

            ...(stores.length > 1 && {
                secondarySource:
                    this.visit(stores[1] as CstorageContext) as ExpressionNode
            })
        };
    }
    visitScore(ctx: ScoreContext): ScoreNode {
        return {
            kind: "Score",

            card:
                this.visit(ctx.card()) as CardNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }

    visitScoremax(ctx: ScoremaxContext): ScoreMaxNode {
        return {
            kind: "ScoreMax",

            collection:
                this.visit(
                    ctx.cstorage()
                ) as ExpressionNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }

    visitScoremin(ctx: ScoreminContext): ScoreMinNode {
        return {
            kind: "ScoreMin",

            collection:
                this.visit(
                    ctx.cstorage()
                ) as ExpressionNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }
    visitAggi(ctx: AggiContext): IntegerAggregateNode {
        return {
            kind: "IntegerAggregate",

            collection:
                this.visit(
                    ctx.collection()
                ) as ExpressionNode,

            variable:
                this.variableName(
                    ctx.var().text
                ),

            storage:
                this.visit(
                    ctx.rawstorage()
                ) as RawStorageNode,
        };
    }
    visitCollection(ctx: CollectionContext): ExpressionNode {

        const candidates = [
            ctx.varc?.(),
            ctx.filter?.(),
            ctx.cstorage?.(),
            ctx.strcollection?.(),
            ctx.cstoragecollection?.(),
            ctx.whot?.(),
            ctx.other?.(),
            ctx.range?.()
        ].filter(Boolean);

        if (candidates.length === 0) {
            throw new Error("Unknown collection");
        }

        return this.visit(candidates[0] as any) as ExpressionNode;
    }
    visitBoolean(ctx: BooleanContext): BooleanNode {

        if (ctx.boolean().length === 2) {

            const op =
                ctx.BOOLOP()?.text === "or"
                    ? "or"
                    : "and";

            return {
                kind: "BooleanOperator",

                operator: op,

                operands: [
                    this.visit(ctx.boolean(0)) as ExpressionNode,
                    this.visit(ctx.boolean(1)) as ExpressionNode,
                ]
            };
        }

        if (ctx.UNOP()) {
            return {
                kind: "Negation",

                value:
                    this.visit(
                        ctx.boolean(0)
                    ) as ExpressionNode,
            };
        }

        if (ctx.int().length === 2) {

            return {
                kind: "Comparison",

                operator:
                    (ctx.intop()?.text ??
                        "==") as ComparisonNode["operator"],

                left:
                    this.visit(ctx.int(0)) as ExpressionNode,

                right:
                    this.visit(ctx.int(1)) as ExpressionNode,
            };
        }

        if (ctx.aggb()) {
            return this.visit(
                ctx.aggb()!
            ) as BooleanAggregateNode;
        }

        if (ctx.str().length === 2) {
            return {
                kind: "Comparison",

                operator:
                    (ctx.EQOP()?.text ??
                        "==") as ComparisonNode["operator"],

                left:
                    this.visit(ctx.str(0)) as ExpressionNode,

                right:
                    this.visit(ctx.str(1)) as ExpressionNode,
            };
        }

        if (ctx.card().length === 2) {
            return {
                kind: "Comparison",

                operator:
                    (ctx.EQOP()?.text ??
                        "==") as ComparisonNode["operator"],

                left:
                    this.visit(ctx.card(0)) as ExpressionNode,

                right:
                    this.visit(ctx.card(1)) as ExpressionNode,
            };
        }

        if (ctx.whop().length === 2) {
            return {
                kind: "Comparison",

                operator:
                    (ctx.EQOP()?.text ??
                        "==") as ComparisonNode["operator"],

                left:
                    this.visit(ctx.whop(0)) as ExpressionNode,

                right:
                    this.visit(ctx.whop(1)) as ExpressionNode,
            };
        }

        if (ctx.whot().length === 2) {
            return {
                kind: "Comparison",

                operator:
                    (ctx.EQOP()?.text ??
                        "==") as ComparisonNode["operator"],

                left:
                    this.visit(ctx.whot(0)) as ExpressionNode,

                right:
                    this.visit(ctx.whot(1)) as ExpressionNode,
            };
        }

        return {
            kind: "BooleanLiteral",
            value: true,
        };
    }
    visitMultiaction(ctx: MultiactionContext): MultiActionNode {

        const agg = ctx.agg();
        if (agg) {
            return this.visit(agg) as AggregateNode;
        }

        const letNode = ctx.let();
        if (letNode) {
            return this.visit(letNode) as LetNode;
        }

        return {
            kind: "Do",
            actions:
                ctx.condact().map(c =>
                    this.visit(c) as ConditionalActionNode
                )
        };
    }
    visitCondact(ctx: CondactContext): ConditionalActionNode {

        const condition = ctx.boolean();

        const action =
            ctx.action()
                ? this.visit(ctx.action()!) as ActionNode
                : this.visit(ctx.multiaction2()!) as MultiActionNode;

        return condition
            ? {
                kind: "ConditionalAction",
                condition:
                    this.visit(condition) as ExpressionNode,
                action
            }
            : {
                kind: "ConditionalAction",
                action
            };
    }

    visitAgg(ctx: AggContext): AggregateNode {
        return {
            kind: "Aggregate",

            aggregateType: "all",

            collection:
                this.visit(ctx.collection()) as ExpressionNode,

            variable:
                this.variableName(ctx.var().text),

            action:
                this.visit(ctx.condact()) as ConditionalActionNode,
        };
    }
    visitLet(ctx: LetContext): LetNode {

        const body =
            ctx.action()
                ? this.visit(ctx.action()!) as ActionNode
                : ctx.multiaction()
                    ? this.visit(ctx.multiaction()!) as MultiActionNode
                    : this.visit(ctx.condact()!) as ConditionalActionNode;

        return {
            kind: "Let",

            variable:
                this.variableName(ctx.var().text),

            variableType:
                this.resolveType(ctx.typed()),

            body
        };
    }
    visitInitpoints(ctx: InitpointsContext): InitPointsNode {
        return {
            kind: "InitPoints",

            storage:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,

            awards:
                ctx.awards().map(a =>
                    this.visit(a) as AwardNode
                )
        };
    }
    visitUpdatepoints(ctx: UpdatepointsContext): UpdatePointsNode {
        return {
            kind: "UpdatePoints",

            storage:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,

            awards:
                ctx.awards().map(a =>
                    this.visit(a) as AwardNode
                )
        };
    }
    visitAwards(ctx: AwardsContext): AwardNode {
        return {
            kind: "Award",

            categories:
                ctx.subaward().map(s =>
                    this.visit(s) as SubAwardNode
                ),

            value:
                this.visit(ctx.int()) as ExpressionNode,
        };
    }
    visitSubaward(ctx: SubawardContext): SubAwardNode {

        const entries = ctx.str();

        return {
            kind: "SubAward",

            left:
                this.visit(entries[0] as StrContext) as ExpressionNode,

            right:
                this.visit(entries[1] as StrContext) as ExpressionNode,
        };
    }
    visitOwner(ctx: OwnerContext): OwnerPlayerNode {
        return {
            kind: "OwnerPlayer",

            card:
                this.visit(ctx.card()) as CardNode
        };
    }
    visitTeamp(ctx: TeampContext): TeamNode {
        return {
            kind: "TeamOfPlayer",

            player:
                ctx.whop()
                    ? this.visit(ctx.whop()!) as PlayerNode
                    : {
                        kind: "PlayerVariable",
                        variable:
                            this.variableName(
                                ctx.varp()!.text
                            )
                    }
        };
    }
    visitFilter(ctx: FilterContext): FilterNode {
        return {
            kind: "Filter",

            source:
                this.visit(
                    ctx.collection()
                ) as ExpressionNode,

            variable:
                this.variableName(
                    ctx.var().text
                ),

            predicate:
                this.visit(
                    ctx.boolean()
                ) as BooleanNode
        };
    }
    visitMaxof(ctx: MaxofContext): CardNode {
        return {
            kind: "Card",

            selector: "max",

            collection:
                this.visit(ctx.cstorage()) as ExpressionNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }
    visitMinof(ctx: MinofContext): CardNode {
        return {
            kind: "Card",

            selector: "min",

            collection:
                this.visit(ctx.cstorage()) as ExpressionNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }
    visitSum(ctx: SumContext): ScoreSumNode {
        return {
            kind: "ScoreSum",

            collection:
                this.visit(
                    ctx.cstorage()
                ) as ExpressionNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }
    visitPid(ctx: PidContext): PlayerIdNode {
        return {
            kind: "PlayerId",

            player:
                this.visit(ctx.whop()) as PlayerNode
        };
    }
    visitTid(ctx: TidContext): TeamIdNode {
        return {
            kind: "TeamId",

            team:
                this.visit(ctx.whot()) as TeamNode
        };
    }
    visitCstorage(ctx: CstorageContext): ExpressionNode {

        const candidates = [
            ctx.varcs?.(),
            ctx.unionof?.(),
            ctx.intersectof?.(),
            ctx.disjunctionof?.(),
            ctx.sortof?.(),
            ctx.filter?.(),
            ctx.basecstorage?.(),
            ctx.memstorage?.(),
            ctx.sequence?.(),
            ctx.runsequence?.(),
        ];

        const found = candidates.find(Boolean);

        if (!found) {
            throw new Error("Unknown cstorage");
        }

        return this.visit(found as any) as ExpressionNode;
    }
    visitBasecstorage(ctx: BasecstorageContext): CollectionStorageNode {

        const owner =
            this.visit(ctx.locpre()) as PlayerNode;

        const location: LocationReferenceNode = {
            kind: "LocationReference",

            owner,

            locationType:
                ctx.locdesc().text,

            ...(ctx.int() && {
                index:
                    this.visit(ctx.int()!) as ExpressionNode
            })
        };

        return {
            kind: "CollectionStorage",
            location
        };
    }
    visitSequence(ctx: SequenceContext): SequenceNode {
        return {
            kind: "Sequence",

            length:
                this.visit(ctx.int()) as ExpressionNode,

            collection:
                this.visit(ctx.cstorage()) as ExpressionNode,
        };
    }
    visitRunsequence(ctx: RunsequenceContext): RunNode {
        return {
            kind: "Run",

            length:
                this.visit(ctx.int()) as ExpressionNode,

            collection:
                this.visit(ctx.cstorage()) as ExpressionNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }
    visitRun(ctx: RunContext): RunNode {
        return {
            kind: "Run",

            length:
                this.visit(ctx.int()) as ExpressionNode,

            collection:
                this.visit(ctx.cstorage()) as ExpressionNode,

            scoreSource:
                this.visit(
                    ctx.pointstorage()
                ) as PointStorageNode,
        };
    }
    visitAggcs(ctx: AggcsContext): AggregateCollectionNode {
        return {
            kind: "AggregateCollection",

            source:
                this.visit(
                    ctx.collection()
                ) as ExpressionNode,

            variable:
                this.variableName(
                    ctx.var().text
                ),

            collection:
                this.visit(
                    ctx.cstorage()
                ) as ExpressionNode,
        };
    }
    visitUnionof(ctx: UnionofContext): CollectionNode {

        const args =
            ctx.cstorage().map(c =>
                this.visit(c) as ExpressionNode
            );

        return {
            kind: "Collection",
            operation: "union",
            arguments: args,
        };
    }
    visitIntersectof(ctx: IntersectofContext): CollectionNode {

        const args =
            ctx.cstorage().map(c =>
                this.visit(c) as ExpressionNode
            );

        return {
            kind: "Collection",
            operation: "intersect",
            arguments: args,
        };
    }
    visitDisjunctionof(ctx: DisjunctionofContext): CollectionNode {

        const args =
            ctx.cstorage().map(c =>
                this.visit(c) as ExpressionNode
            );

        return {
            kind: "Collection",
            operation: "disjunction",
            arguments: args,
        };
    }
    visitSortof(ctx: SortofContext): CollectionNode {
        return {
            kind: "Collection",

            operation: "sort",

            arguments: [
                this.visit(ctx.cstorage()) as ExpressionNode,
                this.visit(ctx.pointstorage()) as ExpressionNode,
            ]
        };
    }

    visitPartition(ctx: PartitionContext): CollectionNode {

        const args =
            ctx.cstorage().map(c =>
                this.visit(c) as ExpressionNode
            );

        return {
            kind: "Collection",

            operation: "partition",

            arguments: args,
        };
    }
    visitSubset(ctx: SubsetContext): CollectionNode {

        const args: ExpressionNode[] = [
            this.visit(ctx.cstorage()) as ExpressionNode
        ];

        if (ctx.int()) {
            args.push(
                this.visit(ctx.int()!) as ExpressionNode
            );
        }

        return {
            kind: "Collection",
            operation: "subset",
            arguments: args,
        };
    }
    visitIndexed(ctx: IndexedContext): CollectionStorageNode {
        return {
            kind: "CollectionStorage",

            location: {
                kind: "LocationReference",

                owner:
                    this.visit(
                        ctx.locpre()
                    ) as PlayerNode,

                locationType:
                    ctx.locdesc().text,
            }
        };
    }
    visitMemstorage(ctx: MemstorageContext): CollectionNode {

        const args: ExpressionNode[] = [
            this.visit(
                ctx.cstoragecollection()
            ) as ExpressionNode
        ];

        if (ctx.int()) {
            args.push(
                this.visit(ctx.int()!) as ExpressionNode
            );
        }

        return {
            kind: "Collection",
            operation: "indexed",
            arguments: args,
        };
    }
    visitStr(ctx: StrContext): ExpressionNode {

        const candidates = [
            ctx.namegr?.(),
            ctx.strstorage?.(),
            ctx.vars?.(),
            ctx.cardatt?.(),
        ];

        const found = candidates.find(Boolean);

        if (!found) {
            throw new Error("Unknown string expression");
        }

        return this.visit(found as any) as ExpressionNode;
    }
    visitCardatt(ctx: CardattContext): FunctionNode {
        return {
            kind: "Function",

            operator: "cardAttribute",

            arguments: [
                this.visit(ctx.card()) as ExpressionNode,
                this.visit(ctx.str()) as ExpressionNode,
            ]
        };
    }
    visitMultiaction2(ctx: Multiaction2Context): MultiActionNode {

        const agg = ctx.agg();

        if (agg) {
            return this.visit(agg) as AggregateNode;
        }

        const letNode = ctx.let();

        if (letNode) {
            return this.visit(letNode) as LetNode;
        }

        return {
            kind: "Do",

            actions:
                ctx.condact().map(c =>
                    this.visit(c) as ConditionalActionNode
                )
        };
    }
    visitLocpre(ctx: LocpreContext): PlayerNode {

        if (ctx.whop()) {
            return this.visit(
                ctx.whop()!
            ) as PlayerNode;
        }

        return {
            kind: "PlayerVariable",

            variable:
                this.variableName(
                    ctx.varp()!.text
                )
        };
    }
    visitLocdesc(ctx: LocdescContext): string {
        return ctx.text;
    }
    visitAggb(ctx: AggbContext): BooleanAggregateNode {
        return {
            kind: "BooleanAggregate",

            collection:
                this.visit(
                    ctx.collection()
                ) as ExpressionNode,

            variable:
                this.variableName(
                    ctx.var().text
                ),

            predicate:
                this.visit(
                    ctx.boolean()
                ) as BooleanNode,
        };
    }
    visitCstoragecollection(
        ctx: CstoragecollectionContext
    ): ExpressionNode {

        const candidates = [
            ctx.partition?.(),
            ctx.subset?.(),
            ctx.run?.(),
            ctx.aggcs?.(),
            ctx.varcsc?.(),
            ctx.indexed?.(),
        ];

        const found = candidates.find(Boolean);

        if (!found) {
            throw new Error(
                "Unknown cstorage collection"
            );
        }

        return this.visit(found as any) as ExpressionNode;
    }
    visitVaro(ctx: VaroContext): VariableNode {
        return {
            kind: "Variable",

            variableKind: "owner",

            name:
                this.variableName(
                    ctx.text
                )
        };
    }
    visitVarc(ctx: VarcContext): VariableNode {
        return {
            kind: "Variable",

            variableKind: "collection",

            name:
                this.variableName(
                    ctx.text
                )
        };
    }
    visitVarcs(ctx: VarcsContext): VariableNode {
        return {
            kind: "Variable",

            variableKind: "cardCollection",

            name:
                this.variableName(
                    ctx.text
                )
        };
    }
    visitVarcsc(ctx: VarcscContext): VariableNode {
        return {
            kind: "Variable",

            variableKind:
                "cardCollectionCollection",

            name:
                this.variableName(
                    ctx.text
                )
        };
    }
    visitVarcard(ctx: VarcardContext): VariableNode {
        return {
            kind: "Variable",

            variableKind: "card",

            name:
                this.variableName(
                    ctx.text
                )
        };
    }


}
